### PR TITLE
Adding Tarot Cards with Images and Explanation to the Wiki Guide

### PR DESCRIPTION
**Pull request by svenjaun**
I wanted to add the Tarot cards to the guide as I believe they would be very helpful to have.

I took the images of the cards from the wiki "https://phasmophobia.fandom.com/wiki/Tarot_Cards".

### CODE REVIEW

**Comment by tybayn** [comment]
Reviewing you PR. 2 issues I see: 
1. I just pushed a massive change to the website, so there are now conflict with the wiki files
2. I don't own the rights to those images and as such they do not fall under the website license and cannot be included in this repo directly.

**Comment by svenjaun** [comment]
I solved the merge conflicts and removed the images.

The current style looks like this:
image
image

**Comment by svenjaun** [comment]
Do you mean with "cannot be included in this repo directly" i should just insert them per Weblink to as example "https://static.wikia.nocookie.net/phasmophobia/images/b/b1/%21TheTower.png/revision/latest"

**Review by tybayn — APPROVED** [review]
Looks good! Thanks for working with me on this!

**Pull request merged**
