### PR TITLE
Fix small typos

### PR DESCRIPTION
**Pull request by Shredder121**
Onyro => Onryo
Some possessives

### CODE REVIEW

**Comment by Shredder121** [comment]
`git show 8928eda6bf2a9c8848dcc9965fb123ae2ab2e669 --color-words=.` highlights the changes if you fetch the branch.

**Comment by tybayn** [comment]
If you can provide the exact changes? This file is produced by a different service and I will need to make the changes there.

**Comment by Shredder121** [comment]
Ah I see.

```diff
diff --git a/old.json b/new.json
index 1836802..1cf885b 100644
--- a/old.json
+++ b/new.json
@@ -86,7 +86,7 @@
       "behavior": [
         "Prefers singing ghost events",
         "Will target a single player (ignoring others while hunting)",
-        "Will roam toward it's target, without leaving EMF 2",
+        "Will roam toward its target, without leaving EMF 2",
         "Banshee scream through paramic  <span class=\"sound\" onClick=\"playSound('assets/banshee_scream.wav')\">🔊</span>",
         "Hunt is always based on target sanity, even if target is outside"
       ]
@@ -104,7 +104,7 @@
         "Freezing"
       ],
       "behavior": [
-        "Ability will drop nearby players sanity by 25% with EMF 2 at the breaker",
+        "Ability will drop nearby players' sanity by 25% with EMF 2 at the breaker",
         "Can not turn off fuse box",
         "<b>Faster when fuse box is on and more than 3m from a seen player</b>"
       ]
@@ -122,7 +122,7 @@
         "Writing"
       ],
       "behavior": [
-        "Hunts at 60% sanity when lights off in the room where its in, 40% when lights on",
+        "Hunts at 60% sanity when lights off in the room where it's in, 40% when lights on",
         "Can not turn on lights",
         "Ability to immediately turn off a light that a player has turned on",
         "Likely to turn off and bust lights"
@@ -142,7 +142,7 @@
       ],
       "behavior": [
         "<b>Faster once the player has been sensed (equipment, voice, or line of sight) and until ghost has reached the players last known location</b>",
-        "Ghost slows down slowly once reaching players last known location"
+        "Ghost slows down slowly once reaching player's last known location"
       ]
     },
     {
@@ -294,7 +294,7 @@
       ]
     },
     {
-      "ghost": "Onyro",
+      "ghost": "Onryo",
       "min_speed": 1.7,
       "max_speed": null,
       "alt_speed": null,
```
Just noticed the context isn't great, these are the ghosts in order of occurence of the changes
- Banshee
- Jinn
- Mare
- Revenant
- Onryo

**Comment by Shredder121** [comment]
Thanks for your work though! Might fiddle a bit myself with the metronome to see if I can get it to work nicer.

**Comment by tybayn** [comment]
Sounds good. I appreciate the fixes and added them to the other service, those changes will be added soon(TM). New feature coming that will force that file to be regenerated. 

Closing PR

**Pull request closed without merging**
